spring:
  application:
    name: music-service
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_MUSIC_URL}
    hikari:
      maximum-pool-size: 20

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

spotify:
  base-url: https://api.spotify.com/v1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance.id:${random.value}}
    hostname: ${HOSTNAME}

server:
  port: 8081

logging:
  level:
    com.tunemate.tunemateplaylist: debug

openapi:
  service:
    version: ${OPENAPI_SERVICE_VERSION}
    url: ${OPENAPI_SERVICE_URL} #api gateway url
springdoc:
  api-docs:
    path: /v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /swagger-ui.html